# Generated by Django 5.2.6 on 2026-03-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('company_name', models.CharField(max_length=150, verbose_name='Название компании')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='Часы работы')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Основной контакт')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('icon', models.CharField(default='bi-layers', help_text='Например: bi-globe2, bi-window, bi-phone.', max_length=100, verbose_name='Иконка Bootstrap')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('order', 'title'),
            },
        ),
    ]
