# Generated by Django 5.2.6 on 2026-06-29 18:16

from django.db import migrations, models


def create_default_home_case_section(apps, schema_editor):
    HomePageCaseSection = apps.get_model('core', 'HomePageCaseSection')
    HomePageCaseSection.objects.get_or_create(
        pk=1,
        defaults={
            'kicker': 'Опыт с админкой',
            'title': 'Aquaklon.ru: контентом и каталогом можно управлять без программиста',
            'body': (
                'На сайте Aquaklon реализована удобная админ-панель на Django, которая позволяет владельцу '
                'самостоятельно управлять контентом без программиста. Через админку можно менять тексты, '
                'контакты, SEO-данные, изображения, отзывы, FAQ, прайс и информацию о доставке. Это делает сайт '
                'не статичной страницей, а полноценным управляемым инструментом для бизнеса. Благодаря админке '
                'заказчик получил возможность быстро обновлять каталог растений, редактировать важные блоки сайта '
                'и поддерживать актуальность информации без обращения к разработчику.'
            ),
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kicker', models.CharField(default='Опыт с админкой', max_length=120, verbose_name='Кикер секции')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст секции')),
                ('image_primary', models.ImageField(blank=True, null=True, upload_to='home/case/', verbose_name='Первая картинка')),
                ('image_primary_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt первой картинки')),
                ('image_secondary', models.ImageField(blank=True, null=True, upload_to='home/case/', verbose_name='Вторая картинка')),
                ('image_secondary_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt второй картинки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Секция кейса на главной',
                'verbose_name_plural': 'Секция кейса на главной',
            },
        ),
        migrations.RunPython(create_default_home_case_section, migrations.RunPython.noop),
    ]
