# Generated by Django 5.2.6 on 2026-03-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('company_name', models.CharField(max_length=150, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('company_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Проект / заказ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('lead', 'Лид'), ('in_progress', 'В работе'), ('support', 'На поддержке'), ('completed', 'Завершен'), ('on_hold', 'На паузе'), ('cancelled', 'Отменен')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('subscription_term_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок подписки, мес.')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен')),
                ('domain_expiration_date', models.DateField(blank=True, null=True, verbose_name='Окончание домена')),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP сервера')),
                ('server_username', models.CharField(blank=True, max_length=150, verbose_name='Пользователь сервера')),
                ('server_password_encrypted', models.TextField(blank=True, verbose_name='Пароль сервера (зашифровано)')),
                ('server_expiration_date', models.DateField(blank=True, null=True, verbose_name='Окончание сервера')),
                ('payment_status', models.CharField(choices=[('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('unpaid', 'Не оплачено'), ('overdue', 'Просрочено')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей оплаты')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='briefs.briefrequest', verbose_name='Связанное ТЗ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-updated_at',),
            },
        ),
    ]
