# Generated by Django 5.2.6 on 2026-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_contact_app',
            field=models.CharField(choices=[('phone', 'Звонок'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='Предпочитаемый способ связи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('lead', 'Лид'), ('in_progress', 'В работе'), ('dns_pending', 'Ожидание обновления DNS'), ('support', 'На поддержке'), ('completed', 'Завершен'), ('on_hold', 'На паузе'), ('cancelled', 'Отменен')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
