# Generated by Django 5.2.6 on 2026-03-28 18:35

from django.db import migrations, models


def populate_client_status(apps, schema_editor):
    Client = apps.get_model("crm", "Client")
    Order = apps.get_model("crm", "Order")
    allowed_statuses = {"new", "in_progress", "dns_pending", "completed"}

    for client in Client.objects.all().iterator():
        latest_order = (
            Order.objects.filter(client_id=client.pk)
            .order_by("-updated_at", "-pk")
            .first()
        )
        if latest_order and latest_order.status in allowed_statuses:
            client.status = latest_order.status
        elif client.is_active:
            client.status = "new"
        else:
            client.status = "completed"
        client.save(update_fields=["status"])


def restore_client_is_active(apps, schema_editor):
    Client = apps.get_model("crm", "Client")

    for client in Client.objects.all().iterator():
        client.is_active = client.status != "completed"
        client.save(update_fields=["is_active"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_simplify_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('dns_pending', 'Ожидание обновления DNS'), ('completed', 'Выполнено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.RunPython(populate_client_status, restore_client_is_active),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
    ]
