# Generated by Django 5.2.6 on 2026-03-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_client_is_active_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Физ. лицо'), ('sole_proprietor', 'ИП'), ('legal_entity', 'Юр. лицо')], default='individual', max_length=20, verbose_name='Тип лица'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_term_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество дней'),
        ),
    ]
