# Generated by Django 5.2.6 on 2026-03-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_client_client_type_order_subscription_term_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячный платеж')),
                ('start_date', models.DateField(verbose_name='Дата старта подписки')),
                ('next_income_date', models.DateField(verbose_name='Дата следующего поступления')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подписка активна')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_subscription', to='crm.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Хостинг-подписка',
                'verbose_name_plural': 'Хостинг-подписки',
                'ordering': ('next_income_date', 'pk'),
            },
        ),
    ]
