# Generated by Django 5.2.6 on 2026-03-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_palette',
            field=models.CharField(blank=True, max_length=255, verbose_name='Палитра проекта'),
        ),
    ]
