# Generated by Django 5.2.6 on 2026-06-29 18:16

from django.db import migrations, models


def backfill_portfolio_fields(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    ProjectImage = apps.get_model('portfolio', 'ProjectImage')
    Technology = apps.get_model('portfolio', 'Technology')

    for index, technology in enumerate(Technology.objects.order_by('name', 'pk'), start=1):
        if technology.order != index:
            technology.order = index
            technology.save(update_fields=['order'])

    for index, project in enumerate(Project.objects.order_by('-completion_date', '-created_at', 'pk'), start=1):
        update_fields = []
        if not project.catalog_order:
            project.catalog_order = index
            update_fields.append('catalog_order')
        if not project.cover_image_alt:
            project.cover_image_alt = project.title
            update_fields.append('cover_image_alt')
        if update_fields:
            project.save(update_fields=update_fields)

    for image in ProjectImage.objects.all():
        if not image.alt_text:
            image.alt_text = image.caption or image.project.title
            image.save(update_fields=['alt_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_color_palette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('catalog_order', '-completion_date', '-created_at'), 'verbose_name': 'Проект портфолио', 'verbose_name_plural': 'Проекты портфолио'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.AddField(
            model_name='project',
            name='catalog_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в каталоге'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt обложки'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt изображения'),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.RunPython(backfill_portfolio_fields, migrations.RunPython.noop),
    ]
