# Generated by Django 5.2.6 on 2026-03-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSMonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('domain', models.CharField(max_length=255, verbose_name='Домен')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('TXT', 'TXT')], default='A', max_length=10, verbose_name='Тип записи')),
                ('expected_value', models.CharField(max_length=255, verbose_name='Ожидаемое значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_status', models.CharField(choices=[('unknown', 'Не проверялось'), ('updated', 'Обновился'), ('not_updated', 'Не обновился'), ('error', 'Ошибка')], default='unknown', max_length=20, verbose_name='Последний статус')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('last_resolved_value', models.TextField(blank=True, verbose_name='Последнее полученное значение')),
                ('last_message', models.TextField(blank=True, verbose_name='Последнее сообщение')),
                ('last_success_notification_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление об обновлении')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_targets', to='crm.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'DNS-цель',
                'verbose_name_plural': 'DNS-цели',
                'ordering': ('domain',),
            },
        ),
        migrations.CreateModel(
            name='DNSCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Проверено')),
                ('status', models.CharField(choices=[('unknown', 'Не проверялось'), ('updated', 'Обновился'), ('not_updated', 'Не обновился'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('resolved_value', models.TextField(blank=True, verbose_name='Полученное значение')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('response_payload', models.JSONField(blank=True, default=list, verbose_name='Сырой ответ')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dns_monitor.dnsmonitortarget', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Лог DNS-проверки',
                'verbose_name_plural': 'Логи DNS-проверок',
                'ordering': ('-checked_at',),
            },
        ),
    ]
