# Generated by Django 5.2.6 on 2026-03-28 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(verbose_name='Дата')),
                ('operation_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, verbose_name='Тип операции')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='crm.client', verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_entries', to='crm.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Операция бухгалтерии',
                'verbose_name_plural': 'Операции бухгалтерии',
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
