# Generated by Django 5.2.6 on 2026-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='reference_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Служебный ключ'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручная'), ('project_payment', 'Оплата проекта'), ('hosting_subscription', 'Подписка на хостинг')], default='manual', max_length=30, verbose_name='Источник'),
        ),
    ]
