# Generated by Django 5.2.6 on 2026-03-28 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('preferred_contact_method', models.CharField(blank=True, max_length=100, verbose_name='Предпочтительный способ связи')),
                ('project_type', models.CharField(choices=[('corporate', 'Корпоративный сайт'), ('landing', 'Лендинг'), ('shop', 'Интернет-магазин'), ('crm', 'CRM / внутренний кабинет'), ('support', 'Поддержка / доработка'), ('other', 'Другое')], max_length=20, verbose_name='Тип проекта')),
                ('company_activity', models.TextField(verbose_name='Чем занимается компания')),
                ('project_goals', models.TextField(verbose_name='Цели проекта')),
                ('target_audience', models.TextField(verbose_name='Целевая аудитория')),
                ('pages_and_structure', models.TextField(verbose_name='Структура и страницы')),
                ('functional_requirements', models.TextField(verbose_name='Функциональные требования')),
                ('design_preferences', models.TextField(verbose_name='Пожелания по дизайну')),
                ('content_status', models.CharField(choices=[('ready', 'Контент готов'), ('partial', 'Частично готов'), ('need_help', 'Нужна помощь с контентом')], max_length=20, verbose_name='Готовность контента')),
                ('integrations', models.TextField(blank=True, verbose_name='Интеграции и сервисы')),
                ('domain_and_hosting', models.TextField(blank=True, verbose_name='Домен и хостинг')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый дедлайн')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет')),
                ('reference_examples', models.TextField(blank=True, verbose_name='Примеры / референсы')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Дополнительные комментарии')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'В работе'), ('proposal', 'Подготовлено предложение'), ('signed', 'Договор подписан'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка / ТЗ',
                'verbose_name_plural': 'Заявки / ТЗ',
                'ordering': ('-created_at',),
            },
        ),
    ]
