# Generated by Django 5.2.6 on 2026-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefrequest',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='company_activity',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='content_status',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='design_preferences',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='domain_and_hosting',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='functional_requirements',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='integrations',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='pages_and_structure',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='project_goals',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='reference_examples',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='business_name',
            field=models.CharField(default='', max_length=150, verbose_name='Название компании / имя'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='color_preference',
            field=models.CharField(choices=[('blue', 'Сине-графитовая гамма'), ('green', 'Зеленая гамма'), ('dark', 'Темные акценты'), ('sand', 'Песочно-бежевые тона'), ('contrast', 'Контрастный стиль'), ('unsure', 'Нужна рекомендация')], default='unsure', max_length=20, verbose_name='Цветовая гамма'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='company_description',
            field=models.TextField(default='', verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='contact_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='design_style',
            field=models.CharField(choices=[('strict', 'Строгий деловой'), ('modern', 'Современный'), ('premium', 'Премиальный'), ('warm', 'Теплый и доверительный'), ('minimal', 'Минималистичный')], default='modern', max_length=20, verbose_name='Стиль сайта'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='briefs/logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='reference_sites',
            field=models.TextField(blank=True, verbose_name='Примеры сайтов'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='region_type',
            field=models.CharField(choices=[('city', 'Один город'), ('region', 'Область / регион'), ('multi', 'Несколько регионов'), ('remote', 'Работаем удаленно')], default='city', max_length=20, verbose_name='Формат региона'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='service_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='services_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Другое направление'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='testimonials_status',
            field=models.CharField(choices=[('ready', 'Отзывы готовы'), ('few', 'Есть несколько'), ('none', 'Пока нет'), ('need_help', 'Нужна помощь в оформлении')], default='none', max_length=20, verbose_name='Отзывы клиентов'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='testimonials_text',
            field=models.TextField(blank=True, verbose_name='Тексты отзывов'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='work_examples_file',
            field=models.FileField(blank=True, null=True, upload_to='briefs/examples/', verbose_name='Файл с примерами работ'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='work_examples_format',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('both', 'Фото и видео'), ('none', 'Пока нет')], default='photo', max_length=20, verbose_name='Примеры работ'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='work_examples_links',
            field=models.TextField(blank=True, verbose_name='Ссылки на примеры работ'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='work_format',
            field=models.CharField(choices=[('company', 'Компания'), ('private_master', 'Частный мастер')], default='company', max_length=20, verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='work_region',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес / регион работы'),
        ),
    ]
