# Generated by Django 5.2.6 on 2026-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0002_remove_briefrequest_additional_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefrequest',
            name='preferred_contact_app',
            field=models.CharField(choices=[('phone', 'Звонок'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='Предпочитаемое приложение для связи'),
        ),
    ]
