# Generated by Django 5.2.6 on 2026-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0003_briefrequest_preferred_contact_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefrequest',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='contact_whatsapp',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='design_style',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='region_type',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='service_categories',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='services_other',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='testimonials_status',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='testimonials_text',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='work_examples_file',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='work_examples_format',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='work_examples_links',
        ),
        migrations.RemoveField(
            model_name='briefrequest',
            name='work_format',
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Физ. лицо'), ('sole_proprietor', 'ИП'), ('legal_entity', 'Юр. лицо')], default='individual', max_length=20, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ориентировочная стоимость'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_domain',
            field=models.BooleanField(default=False, verbose_name='Добавить домен'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_hosting',
            field=models.BooleanField(default=False, verbose_name='Добавить хостинг'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='photos_file',
            field=models.FileField(blank=True, null=True, upload_to='briefs/photos/', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='reviews_file',
            field=models.FileField(blank=True, null=True, upload_to='briefs/reviews/', verbose_name='Скрины отзывов'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='site_type',
            field=models.CharField(choices=[('single_page', 'Одностраничный сайт - визитка / резюме'), ('catalog', 'Сайт-каталог')], default='single_page', max_length=20, verbose_name='Тип сайта'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='texts_file',
            field=models.FileField(blank=True, null=True, upload_to='briefs/texts/', verbose_name='Тексты'),
        ),
    ]
