# Generated by Django 5.2.6 on 2026-03-28 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0004_remove_briefrequest_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefrequest',
            name='color_preference',
            field=models.CharField(default='#14344c', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Желаемые цвета'),
        ),
    ]
