# Generated by Django 5.2.6 on 2026-03-28 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0005_alter_briefrequest_color_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefrequest',
            name='color_accent',
            field=models.CharField(default='#c96f3b', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентный цвет'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='color_background',
            field=models.CharField(default='#f4f1ea', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фоновый цвет'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='color_extra',
            field=models.CharField(default='#2b506b', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Дополнительный цвет'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='color_mode',
            field=models.CharField(choices=[('template', 'По шаблону'), ('custom', 'Кастом')], default='template', max_length=20, verbose_name='Режим выбора цветов'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='color_template_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Выбранный шаблон палитры'),
        ),
        migrations.AlterField(
            model_name='briefrequest',
            name='color_preference',
            field=models.CharField(default='#14344c', max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основной цвет'),
        ),
    ]
