# Generated by Django 5.2.6 on 2026-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0006_briefrequest_color_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefrequest',
            name='client_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий клиента'),
        ),
    ]
