# Generated by Django 5.2.6 on 2026-03-28 16:29

import briefs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0007_briefrequest_client_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.CharField(choices=[('photos', 'Фотки'), ('texts', 'Тексты'), ('reviews', 'Скрины отзывов')], max_length=20, verbose_name='Категория')),
                ('file', models.FileField(upload_to=briefs.models.brief_attachment_upload_to, verbose_name='Файл')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='briefs.briefrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Вложение заявки',
                'verbose_name_plural': 'Вложения заявок',
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
