# Generated by Django 5.2.6 on 2026-03-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0008_briefattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefrequest',
            name='desired_domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Желаемый домен'),
        ),
    ]
