# Generated by Django 5.2.6 on 2026-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0009_briefrequest_desired_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefrequest',
            name='extra_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество доп. страниц'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='hosting_plan',
            field=models.CharField(choices=[('monthly', '1 месяц'), ('quarterly', '3 месяца (-25%)')], default='monthly', max_length=20, verbose_name='Период оплаты хостинга'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_basic_seo',
            field=models.BooleanField(default=False, verbose_name='Базовое SEO продвижение'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_email_form',
            field=models.BooleanField(default=False, verbose_name='Форма с отправкой писем на почту'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_logo_design',
            field=models.BooleanField(default=False, verbose_name='Создание логотипа'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_photo_selection',
            field=models.BooleanField(default=False, verbose_name='Подбор фото и картинок'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_reviews_section',
            field=models.BooleanField(default=False, verbose_name='Секция с отзывами'),
        ),
    ]
