# Generated by Django 5.2.6 on 2026-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0010_briefrequest_extra_pages_briefrequest_hosting_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefrequest',
            name='need_catalog_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Админ панель для редактирования каталога товаров'),
        ),
        migrations.AddField(
            model_name='briefrequest',
            name='need_text_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Админ панель для смены текстов сайта'),
        ),
    ]
