# Generated by Django 5.2.6 on 2026-06-29 18:16

from django.db import migrations, models


def create_default_pricing_settings(apps, schema_editor):
    PricingSettings = apps.get_model('briefs', 'PricingSettings')
    PricingSettings.objects.get_or_create(
        pk=1,
        defaults={
            'site_single_page_price': 3000,
            'site_catalog_price': 4000,
            'extra_page_price': 1000,
            'hosting_monthly_price': 750,
            'hosting_quarterly_price': 1687.5,
            'domain_price': 550,
            'logo_design_price': 500,
            'basic_seo_price': 500,
            'photo_selection_price': 2000,
            'email_form_price': 1500,
            'reviews_section_price': 250,
            'text_admin_panel_price': 2000,
            'catalog_admin_panel_price': 2000,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0011_briefrequest_need_catalog_admin_panel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('site_single_page_price', models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Одностраничный сайт')),
                ('site_catalog_price', models.DecimalField(decimal_places=2, default=4000, max_digits=10, verbose_name='Сайт-каталог')),
                ('extra_page_price', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Дополнительная страница')),
                ('hosting_monthly_price', models.DecimalField(decimal_places=2, default=750, max_digits=10, verbose_name='Хостинг на 1 месяц')),
                ('hosting_quarterly_price', models.DecimalField(decimal_places=2, default=1687.5, max_digits=10, verbose_name='Хостинг на 3 месяца')),
                ('domain_price', models.DecimalField(decimal_places=2, default=550, max_digits=10, verbose_name='Регистрация домена')),
                ('logo_design_price', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Создание логотипа')),
                ('basic_seo_price', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Базовое SEO')),
                ('photo_selection_price', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Подбор фото и картинок')),
                ('email_form_price', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Форма с отправкой писем')),
                ('reviews_section_price', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='Секция с отзывами')),
                ('text_admin_panel_price', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Админ панель для смены текстов сайта')),
                ('catalog_admin_panel_price', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Админ панель для редактирования каталога товаров')),
            ],
            options={
                'verbose_name': 'Настройки цен',
                'verbose_name_plural': 'Настройки цен',
            },
        ),
        migrations.RunPython(create_default_pricing_settings, migrations.RunPython.noop),
    ]
