# Generated by Django 5.2.6 on 2026-03-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('dns_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('days_before', models.PositiveIntegerField(verbose_name='За сколько дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило напоминания',
                'verbose_name_plural': 'Правила напоминаний',
                'ordering': ('days_before',),
                'constraints': [models.UniqueConstraint(fields=('days_before',), name='unique_days_before_rule')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('reference_key', models.CharField(max_length=255, verbose_name='Ключ уникальности')),
                ('event_type', models.CharField(choices=[('subscription', 'Подписка'), ('domain', 'Домен'), ('server', 'Сервер'), ('dns_updated', 'DNS обновился')], max_length=30, verbose_name='Тип события')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('days_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='Осталось дней')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('error', 'Ошибка'), ('skipped', 'Пропущено')], default='sent', max_length=20, verbose_name='Статус')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('dns_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='dns_monitor.dnsmonitortarget', verbose_name='DNS-цель')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='crm.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ('-sent_at',),
                'constraints': [models.UniqueConstraint(fields=('reference_key',), name='unique_notification_reference_key')],
            },
        ),
    ]
