# Generated by Django 5.2.6 on 2026-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('subscription', 'Подписка'), ('domain', 'Домен'), ('server', 'Сервер'), ('dns_updated', 'DNS обновился'), ('hosting_income', 'Доход по хостингу')], max_length=30, verbose_name='Тип события'),
        ),
    ]
